# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import user_pb2 as user__pb2


class UserServiceStub(object):
  """Missing associated documentation comment in .proto file."""
  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateUser = channel.unary_unary(
        '/user.UserService/CreateUser',
        request_serializer=user__pb2.UserCreateRequest.SerializeToString,
        response_deserializer=user__pb2.UserResponse.FromString,
        )
    self.GetUser = channel.unary_unary(
        '/user.UserService/GetUser',
        request_serializer=user__pb2.UserRequest.SerializeToString,
        response_deserializer=user__pb2.UserResponse.FromString,
        )


class UserServiceServicer(object):
  """Missing associated documentation comment in .proto file."""
  def CreateUser(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUser(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=user__pb2.UserCreateRequest.FromString,
          response_serializer=user__pb2.UserResponse.SerializeToString,
      ),
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=user__pb2.UserRequest.FromString,
          response_serializer=user__pb2.UserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'user.UserService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class UserService(object):
  """Missing associated documentation comment in .proto file."""
  @staticmethod
  def CreateUser(request,
      target,
      options=(),
      channel_credentials=None,
      call_credentials=None,
      insecure=False,
      compression=None,
      wait_for_ready=None,
      timeout=None,
      metadata=None):
    return grpc.experimental.unary_unary(
        request, target, '/user.UserService/CreateUser',
        user__pb2.UserCreateRequest.SerializeToString,
        user__pb2.UserResponse.FromString,
        options, channel_credentials,
        insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def GetUser(request,
      target,
      options=(),
      channel_credentials=None,
      call_credentials=None,
      insecure=False,
      compression=None,
      wait_for_ready=None,
      timeout=None,
      metadata=None):
    return grpc.experimental.unary_unary(
        request, target, '/user.UserService/GetUser',
        user__pb2.UserRequest.SerializeToString,
        user__pb2.UserResponse.FromString,
        options, channel_credentials,
        insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
