TIMESTAMP_MAXIMUM_DELAY_THRESHOLD = 5 * 60 # seconds
ACCURACY_THRESHOLD = 15 # meters
MAXIMUM_SPEED_THRESHOLD = 150 # km/h
KEEP_LAST_LOCATIONS_COUNT = 5

MAXIMUM_LOCATION_TO_STORE_PER_DRIVER = 20
LOCATIONS_CACHE_TTL = 30 * 60 
